linters:
  eslint:
    enabled: true
    config_file: .eslint.config.js
    file_patterns:
      - '*.js'
      - '*.ts'
    enabled_plugins:
      - eslint-plugin-react
      - eslint-plugin-import
      - eslint-plugin-prettier
      - eslint-plugin:@typescript-eslint
